insert into  itemcategorycode (itemcode, description) values ('01','Rauðvín');
insert into  itemcategorycode (itemcode, description) values ('02','Hvítvín');
insert into  itemcategorycode (itemcode, description) values ('03','Rósavín');
insert into  itemcategorycode (itemcode, description) values ('04','Freyðivín');
insert into  itemcategorycode (itemcode, description) values ('05','Styrkt vín');
insert into  itemcategorycode (itemcode, description) values ('06','Ávaxtavín');
insert into  itemcategorycode (itemcode, description) values ('10','Brandí');
insert into  itemcategorycode (itemcode, description) values ('11','Ávaxtabrandí');
insert into  itemcategorycode (itemcode, description) values ('13','Viskí');
insert into  itemcategorycode (itemcode, description) values ('14','Romm');
insert into  itemcategorycode (itemcode, description) values ('15','Tequila o.fl.');
insert into  itemcategorycode (itemcode, description) values ('16','Ókryddað brennivín og vodka');
insert into  itemcategorycode (itemcode, description) values ('17','Gin & sénever');
insert into  itemcategorycode (itemcode, description) values ('18','Snafs');
insert into  itemcategorycode (itemcode, description) values ('20','Likjorar');
insert into  itemcategorycode (itemcode, description) values ('21','Bitterar, kryddvín, aperitífar');
insert into  itemcategorycode (itemcode, description) values ('23','Blandaðir drykkir');
insert into  itemcategorycode (itemcode, description) values ('29','Óáfeng vín');
insert into  itemcategorycode (itemcode, description) values ('60','Lagerbjór');
insert into  itemcategorycode (itemcode, description) values ('61','Öl');
insert into  itemcategorycode (itemcode, description) values ('62','Aðrar bjórtegundir');
insert into  itemcategorycode (itemcode, description) values ('79','Óáfeng vín');
insert into  itemcategorycode (itemcode, description) values ('80','Rekstrarvörur');
insert into  itemcategorycode (itemcode, description) values ('81','Iðnaðarvara - neftóbak');
insert into  itemcategorycode (itemcode, description) values ('82','Umbúðir og aðrar söluvörur');
insert into  itemcategorycode (itemcode, description) values ('89','Niðurlagðir ávextir');
insert into  itemcategorycode (itemcode, description) values ('90','Neftóbak');
insert into  itemcategorycode (itemcode, description) values ('91','Reyktóbak');
insert into  itemcategorycode (itemcode, description) values ('92','Vindlingar');
insert into  itemcategorycode (itemcode, description) values ('93','Vindlar');
insert into  itemcategorycode (itemcode, description) values ('94','Munntóbak');
